stages:
- build
- test
- deploy
sast:
  stage: build
  script: 
  - cd /home/gitlab-runner/wsapiintegracion
  - git stash
  - git checkout main
  - git pull origin main
include:
- template: Security/SAST.gitlab-ci.yml
#test