stages:
- build
- test
- deploy


Build Job:
  stage: build
  script:
    - git fetch --all
    - git pull origin main
  artifacts:
    paths:
    - /home/gitlab-runner/wsapiintegracion

Test Job:
  stage: test
  script:
    - git fetch --all
    - git pull -f origin test
  artifacts:
    paths:
    - /home/gitlab-runner/wsapi-test


Deploy Job:
  stage: deploy
  script:
    - echo "Job Deploy"

include:
    - template: Security/SAST.gitlab-ci.yml