stages:
- build
- test
- deploy

Build Job:
  stage: build
  script: 
  - cd /home/code/wsapiintegracion
  - git stash
  - git checkout main
  - git pull origin main

Test Job:
  stage: test
  script:
    - echo "Jab Test"

Deploy Job:
  stage: deploy
  script:
    - echo "Job Deploy"

include:
    - template: Security/SAST.gitlab-ci.yml